### ISSUE TITLE
Apple not providing a way to download personal data

### ISSUE THREAD

**Issue by meny** [google/data-transfer-project#1055]
Apple is not providing a sensible way to download users' data from their servers. I believe this is in conflict with EU law, but in any case hindering users' access to their own data. As an example companies such as Google, Facebook, Flickr, and others provide dedicated options for downloading of personal data.

A good example is Apple's support page describing how users are expected to download their data:
[https://support.apple.com/en-us/HT204055](https://support.apple.com/en-us/HT204055)

For instance, downloading of notes stored in iCloud is suggested as follows:

> Open the Notes app and select the note that you want.
> Click File > Export as PDF. 
> Choose where to save the document to your computer.

Apple's method described above is unthinkable for hundreds of notes, and this is just one example.

**Comment by DrPyser** [comment]
I would add for this example that a PDF export is not a sensible format for interoperability purposes. It's an opaque view-only medium. A suitable common/openly specified text format that can easily be transformed to other formats would be needed to really serve interoperability.
