### ISSUE TITLE
Add ImportableItem interface to all data models

### ISSUE THREAD

**Issue by wmorland** [google/data-transfer-project#1094]
Se #1079 for an example. This will allow us to better use the new model of IdempotentImportExecutor.

**Comment by xokker** [comment]
19fcc4635f0003ee5200c99c68ca16f1a534fd34 covers a bunch of cases

**Comment by parishrutk** [comment]
Hey There, I am looking to contribute something to the open source project and I thought what better place than google's repos. Could somebody enlighten me on how to contribute more using Java? Really looking forward...
