### ISSUE TITLE
Remove dependency on jcenter

### ISSUE THREAD

**Issue by wmorland** [google/data-transfer-project#1115]
A follow up from #1090

**Comment by seehamrun** [comment]
Is this similar to the issue in #1022 ?

**Comment by xokker** [comment]
@seehamrun I am not sure it is. Looks like #1022 is about shadow plugin, unlike jcenter dependency that we have to keep because of the docker plugin.

Now we are on Gradle 6 I think it makes sense to move to the latest versions of all the plugins. Hopefully it will fix everything.
