### ISSUE TITLE
Migrate Existing Google and In-Memory storage layers to cloud extensions

### ISSUE THREAD

**Issue by holachuy** [google/data-transfer-project#126]
The MS Cosmos extension serves as a good example.

**Comment by rtannenbaum** [comment]
FYI I already migrated the Google & In-Memory JobStores in https://github.com/google/data-portability/pull/113 and removed the old PersistentKeyValueStore

but we still have to handle BucketStore, KeyManagementSystem, and JobDataCache, as well as how to instantiate these in the new modular way (we are currently using CloudFactory)

**Comment by rtannenbaum** [comment]
Also, they are not fully migrated yet since they still used LegacyPortabilityJob

need to finish porting PortabilityJob first (https://github.com/google/data-portability/issues/132)
