### ISSUE TITLE
Wire up AuthServiceProviderRegistry

### ISSUE THREAD

**Issue by holachuy** [google/data-transfer-project#127]
Wire up AuthServiceProviderRegistry, perhaps similarly to the TransferServiceProviderRegistry

**Comment by seehamrun** [comment]
Implementation for this is completeish (#139) but the registry is currently empty as nothing is hooked up or registered with it. The remaining TODO on this bug is to wire it up

**Comment by seehamrun** [comment]
This is complete. All the auth providers are hooked up and accessible
