### ISSUE TITLE
Update gcp script to use gradle based docker build

### ISSUE THREAD

**Issue by holachuy** [google/data-transfer-project#323]
GCP script needs to be modified to use new resources directory that was modified in moving docker build to gradle

**Comment by rtannenbaum** [comment]
Actually, I'm going to close this because I think we can get rid of the GCP build_docker_image script altogether in favor of doing it in build.gradle. I added a comment about that to #236

**Comment by rtannenbaum** [comment]
Reopening since static content script needs to be updated to handle the new resources/ dir
