### ISSUE TITLE
Introduce Gradle build and module structure

### ISSUE THREAD

**Issue by jimmarino** [google/data-transfer-project#35]
This will involve quite a bit of work that will be done in steps via pull requests. 

The first step will be to create a parallel project structure using Gradle that we can discuss and iterate on. Initially, this structure will contain the principal modules as well as a limited number of interfaces and types. 

As the structure stabilizes and people are happy with it, we will make the Gradle modules available through the Maven build so that the new interfaces can be implemented throughout the codebase. 

When the existing code has been migrated we can do a cut-over.

**Comment by seehamrun** [comment]
Blocks #21 (Switch from Maven to Gradle)

**Comment by holachuy** [comment]
I believe the remaining work is to wire up the launchers for the gateway/api and the worker
