### ISSUE TITLE
Make job polling interval configurable

### ISSUE THREAD

**Issue by olsona** [google/data-transfer-project#400]
It should be easier to configure the job polling frequency.  Right now you have to go into JobPollingService.java.

**Comment by mohasaid** [comment]
I could try to fix it, which would be the best option to achieve job polling frequency value from? Gradle.properties?

**Comment by burakfahri** [comment]
I can try to fix it, Mohasaid has asked for it but nobody has answered. Which would be the best option to poll frequency value? From Gradle.properties or under the resources or something else?

**Comment by olsona** [comment]
Sure, if you can get it done in the next day or so that'd be pretty sweet!  We were thinking of making it environment-specific, so in a transfer.yaml file under resources/config would be great.

**Comment by olsona** [comment]
#574
