### ISSUE TITLE
Add a vertical for Blobby storage

### ISSUE THREAD

**Issue by bwillard** [google/data-transfer-project#499]
The goal is to facilitate the transfer of data from products like: Google Drive, DropBox, OneDrive, Box.

I *think* that documents can just be exported in either MS or OpenOffice format and they will be handled correctly on import.

**Comment by rabimba** [comment]
Hi,
Would love to take this issue up. Any pointers on where I should start?

**Comment by chandramoulirajagopalan** [comment]
I would like to contribute to this issue

**Comment by chandramoulirajagopalan** [comment]
I am working on creating a blobby storage transfer for this right now. Can someone guide me when needed ?

**Comment by bwillard** [comment]
Absolutely, feel free to ask any of the maintainers questions, we are all happy to help out.  Either in this issue or via Slack, or we are happy to hop on a Slack/Skype/Hangout with you and walk through things in real time if that is easier.

**Comment by chandramoulirajagopalan** [comment]
Do you have a particular day for meeting and all or are you people available all the time. Can you just tell me the name of the channel or slack username or even skype / hangout is also better. Yes I need to get certain things clarified about the project. I am available daily from now on.

**Comment by bwillard** [comment]
For the Data Model, I think we want to stop just making them up and start using more established models,  for blobby storage I think a subset of https://schema.org/DigitalDocument might work, I think at the very least we can give it a shot and change if needed.

**Comment by chandramoulirajagopalan** [comment]
@bwillard  I gave a look into the schema. Anything else needed to be taken care of ?

**Comment by bwillard** [comment]
I don't think so, I am adding a Google Drive adapter for it, and after that it should be pretty straightforward to add a bunch more adapters.
