### ISSUE TITLE
Package Naming Issue in Twitter Extension

### ISSUE THREAD

**Issue by kutluhanmetin** [google/data-transfer-project#500]
In master branch there is a naming issue in module "portability-data-transfer-twitter". The actual package name is "org.dataportabilityproject.transfer.twitter" however in classes it is written as "org.datatransferproject.transfer.twitter".

**Comment by kutluhanmetin** [comment]
I want to fix the issue but couldn't decide which naming is better.

**Comment by rtannenbaum** [comment]
Hey @kutluhanmetin, thanks for finding this issue. Data Transfer Project is our new project name so the datatransferproject package name is the one that should be used. That should be what we are using elsewhere for our other transfer extensions. Feel free to send me a pull request (that makes the Twitter transfer extension consistent with the others, like https://github.com/google/data-transfer-project/tree/master/extensions/data-transfer/portability-data-transfer-instagram/src/main/java/org/datatransferproject/transfer/instagram).

**Comment by kutluhanmetin** [comment]
Hey @rtannenbaum I sent you a pull request for this.
