### ISSUE TITLE
Publish artifacts to Maven Central

### ISSUE THREAD

**Issue by wmorland** [google/data-transfer-project#580]
We would really like to have the artifacts published in Maven Central so that they can be easily imported and tracked and each user of the project doesn't have to set up their own build pipeline to stay up to date. This could be done either directly via their Open Source Software Repository Hosting https://central.sonatype.org/pages/producers.html or via another repository such as jcenter https://github.com/bintray/gradle-bintray-plugin#maven-central-sync

This would require some additions to the gradle scripts as well as registering with Maven Central and setting up a key for signing the artifacts.

**Comment by jimmarino** [comment]
Hi William,

I'm looking into this now via JCenter. Let me write-up a description of what I'm thinking later today or earl morning tomorrow and we can discuss via this thread or Slack.

**Comment by wmorland** [comment]
Hi Jim, thank you for laying everything out so clearly.

I can only speak for our use case which seems to fit into number 2 of the goals. We need it for hooking into proprietary cloud infrastructure rather than a particular need for private data transfer or auth extensions. It is preferable for us to have a private repository that depends on the public DTP artifacts compared to maintaining a private fork or running a private build pipeline + dependency management.

- I believe the reason Maven Central is preferred as the repository is that JCenter does not require signed binaries (I may be wrong on this).
- There isn't a need for a starter project from us but I can see how it might be useful.

**Comment by jimmarino** [comment]
That's a good point about singing artifacts. I've started a PR with configuration that produces Maven artifacts here:

https://github.com/google/data-transfer-project/pull/582

I'll iterate on that and add in support for signing. Once we have that and JCenter and Maven Central repos to publish to, we should be able to easily replicate from the former to the latter.
