### ISSUE TITLE
PortabilityJob State is never persisted in any jobstore

### ISSUE THREAD

**Issue by seehamrun** [google/data-transfer-project#670]
ex: GoogleJobStore updatejob uses .toMap() to write the job to datastore, but that doesnt populate the Jobstate so its never persisted. http://go/gh/google/data-transfer-project/blob/master/extensions/cloud/portability-cloud-google/src/main/java/org/datatransferproject/cloud/google/GoogleJobStore.java#L175

When we use .fromMap() the jobstate is also always set to NEW

http://go/gh/google/data-transfer-project/blob/master/portability-spi-cloud/src/main/java/org/datatransferproject/spi/cloud/types/PortabilityJob.java#L136

**Comment by rtannenbaum** [comment]
https://github.com/google/data-transfer-project/issues/191 coming back to bite us. really easy to drop fields.
