### ISSUE TITLE
Feature request (Google Photos import): make album name prefixing optional

### ISSUE THREAD

**Issue by anotherchrisberry** [google/data-transfer-project#762]
In the photos importer, albums are always prefixed with `Copy of `. I know there's a `TODO` to i18n-ize it, but it would be nice if there were a way to omit the prefix altogether. 

We're planning to ask users to supply a name for the new album, and don't want `Copy of ` prepended to that. 

It's possible tools might want to name the albums themselves, e.g. `Flickr Export (04 October 2019)`.

https://github.com/google/data-transfer-project/blob/f1ff5b233ca291125436bcfec0c92fb8551fbd99/extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosImporter.java#L46

Thanks for considering this!

**Comment by seehamrun** [comment]
Sure if you want to make this configurable, you can add it to the settings and read the setting from the extensioncontext at initialization time: https://github.com/google/data-transfer-project/blob/master/extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/GoogleTransferExtension.java#L68  

Ex: you would pull look up the var like this 
`String imported_photos_album_prefix = context.getSetting("imported_photos_album_prefix", "");` 

and pass it along to the photos importer when it gets created - the setting can then be adjusted in the config

**Comment by seehamrun** [comment]
We've removed the copy of prefix in #991
