### ISSUE TITLE
Implement KoofrPhotosExporter and KoofrVideosExporter

### ISSUE THREAD

**Issue by bancek** [google/data-transfer-project#933]
Koofr adapter was added to the project in #927. At the moment it only supports imports for photos and videos.

Implement `KoofrPhotosExporter` and `KoofrVideosExporter` so the imported photos and videos can also be exported. The exporters will use the same folder structure as the importers.

To cover import and export of all files `KoofrBlobImporter` and `KoofrBlobExporter` are planned in the future.

This Issue can be assigned to me.

**Comment by marleyjustin08** [comment]
###

**Comment by marleyjustin08** [comment]
extensions/data-transfer/portability-data-transfer-koofr/src/main/java/org/datatransferproject/transfer/koofr/KoofrTransferExtension.java
