### ISSUE TITLE
Please Open a Security Advisory

### ISSUE THREAD

**Issue by JLLeitschuh** [google/data-transfer-project#954]
Hello,

I'm an independent security researcher performing security research under the [GitHub Security Lab Bug Bounty Program](https://securitylab.github.com/). I believe I may have found a security vulnerability in this project.

Please open a security advisory against this repository so we can privately discuss the details. This advisory can be opened by a user with admin permissions on this repository.

https://github.com/google/data-transfer-project/security/advisories

**Comment by seehamrun** [comment]
Hiya! thanks we've received this report internally and are working on a fix!

**Comment by JLLeitschuh** [comment]
Hi,
How can I best track this to completion?

**Comment by seehamrun** [comment]
Hey! Sorry for the miscommunication, this is being tracked as a regular issue since the code is self contained - we'll be working on it when we get open cycles

I've opened up #968 to track this - lmk if you still have any questions!

**Comment by JLLeitschuh** [comment]
What's the plan for CVE issuance here?
