### ISSUE TITLE
Make temp file location configurable in Jobstore

### ISSUE THREAD

**Issue by seehamrun** [google/data-transfer-project#968]
We use `File.createTempFile` in the PerJobDatastore because a Random Access file is needed for some apis. This is currently only the GoogeVideoImporter and the BackblazeImporters: https://github.com/google/data-transfer-project/search?q=getTempFileFromInputStream

However `File.createTempFile` creates files in the the system temporary directory with file permissions -rw-r--r-- by default.

We'll need to figure out how to hold the file in memory somehow and still be comptiable with the APIs or simply make the location configurable.

**Comment by JLLeitschuh** [comment]
Or move to the new `Files` API which correctly sets the file permissions on temporary files to be restricted.

**Comment by JLLeitschuh** [comment]
https://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html#createTempFile(java.nio.file.Path,%20java.lang.String,%20java.lang.String,%20java.nio.file.attribute.FileAttribute...)

**Comment by JLLeitschuh** [comment]
Hi all, what's the disclosure/CVE issuance plan for this vulnerability?

**Comment by JLLeitschuh** [comment]
I've reached out to Google multiple times about getting a CVE issued for this vulnerability without response. At this point, I'll be moving forward with the CVE appeals process to get CVEs issued for this vulnerability.

**Comment by JLLeitschuh** [comment]
This vulnerability has been publicly disclosed here: https://github.com/JLLeitschuh/security-research/security/advisories/GHSA-22c6-wcjm-qfjg
